In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score, log_loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier

In [3]:
import pandas as pd

In [4]:
classifiers = [DecisionTreeClassifier(),
              RandomForestClassifier(), 
               AdaBoostClassifier(), 
               GradientBoostingClassifier()]
log_cols = ['Classifier','Accuracy']
log = pd.DataFrame(columns=log_cols)

In [5]:
samples = StratifiedShuffleSplit(n_splits=10, test_size=0.1, random_state=0)

In [6]:
samples

StratifiedShuffleSplit(n_splits=10, random_state=0, test_size=0.1,
            train_size=None)

In [7]:
train = pd.read_csv('data/train_final.csv')
test = pd.read_csv('data/test_final.csv')

In [8]:
train.head()

,Unnamed: 0,Survived,Pclass,Sex,Age,Fare,Embarked,FamilySize,IsAlone,Title
0,0,1,1,1,1,0,1.0,1,1,1
1,1,1,1,0,3,4,1.0,2,0,3
2,2,1,3,0,2,1,0.0,1,1,2
3,3,1,1,0,3,4,0.0,2,0,3
4,4,0,3,1,3,1,0.0,1,1,1

In [9]:
test.head()

   Unnamed: 0  Pclass  Sex  Age  Fare  Embarked  FamilySize  Title  IsAlone
0           0       3    1    3   0.0         2           1      1        1
1           1       3    0    4   0.0         0           2      3        0
2           2       2    1    4   1.0         2           1      1        1
3           3       3    1    2   1.0         0           1      1        1
4           4       3    0    1   2.0         0           3      3        0

In [10]:
train.shape

(891, 10)

In [11]:
train.columns

Index(['Unnamed: 0', 'Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked',
       'FamilySize', 'IsAlone', 'Title'],
      dtype='object')

In [12]:
X = train.drop(['Survived'],axis=1)
y = train['Survived']

In [13]:
X.shape, y.shape

((891, 9), (891,))

In [14]:
for train_index, test_index in samples.split(X,y):
    print(train_index)
    print(test_index)

[349 134 487 519 225  30 129 580 103 649 128 137 209 177 809 542 404 632
 130 475 254 385 266 290 686 119 300 285 464 131 843 703 456 255 234 341
 430 444 662  66 124 447 698 605 116 844 299 702 102 614 775  27  58 427
 410  77 123 830  18 238 529 685 826 164 799 690 885 839   2 438 591 226
 638 409 556 120 126 125 537 567  86 327 545 755 787  13 472 560 797 823
 170 135 117 288 305 503 233 147 767 435 273 717 619 513 520 523 432 471
 247 152 530 563 550 516 399  89 804 198 802 596 240 262  35 581 814  12
 509  67  29 515 590 757 205 776 594 588 807 150 283 714 665 571 627 319
 308 848 424  65 652 180 357  81 148 522 312 762 364 185 406   6 190 750
 352  47 634 201  59 369 883 538 793  41 525 463 880 602 859 849 189 257
 536 239 159 695 114 264 697 479 315 309 527 615 524 484 803 656 606 789
 366  56 488 166 429 636 663 470  95 473 667 461 269 163 688 806 608 242
 815 733 783 338 505  99 584 650 365 756 351  17 681 310 600 379 732 684
 820 183 860 498 771 701 821 715 219 546 502 630 199 693 873 232   1  19
 575 554 621  57 613  82  49 382 604 249 453 570  40 151 528 393 455 263
 812 286 306 673 386  50 585 436 862  11 654 441 758 465 817 106  62 317
 850 845 331 462 612 744 670 346 203 101 837 371 448 739 497 816 113  24
 167 819 532 772  61 127 766 858 562 350 329 110 539 564 105 454 707 478
 531 841 274 710 354 268 659  74 215 765 752 521 179 857 805 380 623 138
 426 889 449 553 348 321 200  20 334 624 867 692 796 111 810 356 811  39
 699  37 298 890  22  31  43 691 625 140 779 610 378 370 422 153 367 651
 565 387 832  23  96 265 589 342 451 139 616 303 786  16 174 548 886  15
 173 734 194 252 853 372 413   5 738 358 877   8 742 156 373 682 256 316
 227 425 218 836 210 660 326 543 343 887 568 743 221  69 467 719  21 499
  80 555 773 360 281 881 347 388 648 782 375 716 376 277 769 184  72 728
 828 469 204 408 253 322 726 398 876 446 593 243 325 212 852 617  91 653
 633 753  92 480 639 780 333 149 763  28  84 501 214 122 865 547 313 647
 459 791   0 162 729  63 874 781 235 540 496 720 175 208 551   4 718 136
 434 582 482 706 512 785  45 642 784 318 477 708 222 397 328 390 722 700
 759 259  88 494 607 421 861 559  85 241 304 500 244 324 611 704 485 671
 433 287 888 236 457 157 552 414 301 696 272 431 601 402 423 856 230 535
 644 246 359 192 583 740 834  70 829 526 678 609 458  73 295 213 133 518
  64 689 374  55  93 291 420 725 490 121 549   9 777 731 741 468 587 452
 311 362 144 237 340 747 855 669 146 822 108 631 450 245 216 335 155 320
 626  60  38 723 770 599 411 207 798 573 847  94 363 171  68  76 760 332
 679 884 276 270 384  78 104 840 416 510 181 749 248 282  83 289 788 418
 569 400 292 635 827 871 872 730 646 661  46 158 160 712 460 489 658 705
 761 517 578 280 381 132 250 764 687 870 576 869 344 748  25 813  34 875
 439 514  79 795  52 745 754 278 172 251 674 713 664 595 261 293 186 579
 231 668 345 115  36 574 620 868 677 314 193  10  14  75  48 736 195 228
 109 481 412 629 107 307 154 141 491 561 863  32 297  90 879 557 220 628
 825 339 778 182 878 492 391 735  97 835 187  98 323 774  42 442 711 217
 165 294 882  53 466 504 866 476 260 655 302 508 724 534 407 544 395 746
 419 694 603 112 296 337 666 178 833 118 622 415 403 202  71 197 507 474
 191  33 206 794 161   7 598 846 533]
[657 336 641 597 838 389 417 709 405 443 751 586 353 279 790 428 572 176
 143 169  51 800 229 824 676 100 223 377  44 506 737 211 396 801 271 284
 224 558 355 672 188 368 483 258 721 142 168 486 680 196 493 440  87 383
 361 275 637 851 618 854 818 842 145  54 330 808 401 495 727 394 541 792
 392 640 437 592 683 511 445 267 566 864 768 645   3 577 643 831  26 675]
[390 834 793 129 807 624 759 679 354  81 837 744 407 411 102 288 402  17
  50 355 728 121 651 524 241 237 410 875 632 274 195 685 258 789 360 531
 545 757 729 488 871  51 265  85 711 674 770 123 300 520 419 335 731 864
 332 845 269 286 715 648 144 862 312 659 264 867 512 618 134 642 879   4
 110 672 572 308 668 794 795 232 200 831 208 733 883 505 294 695 527 255
 507 323 379 263 832 664 565 293 559 458 491 753 532  45 416 823 805 180
 189 689 375  23 738  43 693 667  35 251 802 583 623 880  61 568 469 854
 612  28 334 171 187 560 776 658 809 106 412 551 330 876 660 150 161 138
 304  32 318 172  44 472 751 847 601 429 574  56 842 740 427 403 438 273
 855 848 446 149 320 155 554 857 117 820 850 811 457  22 382 349 235 563
 352 454 670  72  68 441 109 388 116 421 351 219 444 445 853 392 482 137
 179 466 433 779 126 450 636  47 306 523 136 341 281 479  99 148 708   2
 173 254 515  12  18 690  94 626 350 755 746 730 279 710 869 283 408 477
 722 798   1 650 705 790 376 877 221 453  83 158 503 270 301 882 797 567
 561 653 758 496 319 737 615 861 224 732  88  29 303 885 682 772 203 314
 541  86 380 765 474 447  33 125 234 229 698 609 644 522 367 157 259 145
 717 635 780  58 881 593 206 249  59 170 735 701 345 361 814 677 164 762
 769 654 343 211 852 777  64 619  52 167 610 101 803 178 745  67   9 778
 691  27 878 743  74  55 498 613 401 686 365 707 502 750 500 362 336 346
 627 553 302 756 723 202 287 587 378 185 671 712 107 786 253 521 767   3
 866 596 456 856  53 282 326 471 485 838 886 139 452  79 418  70 509 643
 718 151 709  37 806 409  24 371 846 603 478  71 564 464 840 812 605 859
 782 124 162 634 501 536 641 804 547 476 607 120 835 108 487  92 331 606
 398 578 639  41 673 865 716 555 771 517 280  75 787 414 580 692 600 590
 775 598 358 455 726 385 662 448 752 519  42 829 153 873 131 440 344 739
 212 386 141 327 196 182 839 245 284 311 544 431 329 719 278 260  66  96
 703 526 872 205 611 724 100 652 858 399 357 713 103  21 113 540 749  91
 169 204 436  65  54 666 114 465 720 542 530 492 655  34 533 190  36 111
 267 220 404  82 581 470 394 628 317 439 443 400 181 372 213  20 248 146
 468 889  76 297 285 216 339 783 538  89 118 849 585 243 614 163 338 154
  73 602 460 236 484 552 543 808 383 586 694 622   6 324 800 370 833 238
 156 191 781 430   8 347 437 816 266 766 413 177 528 788 550 321 579 261
 425 397 348 377 222 112 884 675 272 215 841 499 363 175 617 268 493 497
 192 577 727 423 688 242 661 127 223 442  46 506 714 462 246 387 316 143
 239 588 176 592  39 676 426 663 525 591 159 322  87 140 748 763 218 291
 396 250 463 569 467 508 702 132 340 573 296 819 697 119   5 640 576 174
 395 271 381  97 359 434 571 828 292 638 890 147 784 706 473 384 791 315
 298 620 599 165  30 198  77 209 309 230  16 366 683 681 511 570 225 105
 201  98 240 194  14 428 844 637  49  48 475 799 687 817  95 562 142 761
 824 342 489  78 364 821 494 818 796 725 589 657 228 630 422 516 247 197
 461 810 299 262 504 633 792  38  84 277 773 244 604 128 226 183 510 874
  90 166 518 313 815 827 825 199 451 557 575 801 188 870 389 420 356 836
 734 830  40 645 546 295  57 631 699 305 680 184 391 337 548 649  69 704
 594 822 415  60 480 435 122 558 669 549  31 373 537 608 843 231 665  80
 566  11 104 310 747 186  63 696 252]
[152 826 764 160 863 405 406 168 754  25 307 584 887 207 684 290  13 495
 513 227 647 374 115 736 256 616 741 514 760 656 449 678  62 130 625 233
 486 860 257  19 629 483 700 742 534 214 868 276 135 325 597   7  15 646
 529 289 353 133 851 774 217 275 333 785   0  26 539 424 393 888 621 417
 432  10 481 369 490 535 813 721 328  93 210 556 582 193 768 368 595 459]
[699 174 833 522  37   8 820 237 109 755 656 700 418 202  56 364 720  11
 799 624 246   7 309 449 605 644 668 633 586 484 576 710 374 808 470 250
 607 813 765 513 448 334 812 678 816 451 587  86 568 645 134 261 620 714
 558 481 631 478 251 157 740 638 884 801 125 599  35  80 397  98 705 163
  54 339 871  90 411 701 143 738 322 284  17 195 547 219 612 318 104 554
 454 139 821 147 107 379 175 239 658 435 777 537 471 325 292 117 144  52
 191 446 752 370 118 199 316 140 634  88 550 698 461 263 469 283 321  84
 797 458 291 336 457 716 608 563 127 877 591 541 110  26 617 856 683 673
 601 665 845 875 351 757 317 868 327 243 567 529  33 763 260 781 231 501
 538 348  70 120 862 274 466 343 751 179 302 252 639  66 709 842  78 542
 363 436 636 494 124 113 516 649 506 859 220  31  57 767 660 600 282 416
 344 352  49 885 846 148 167 817 782   4 387 224 438 400 245 860  47 204
 704 426 384 580 405 323 168 346 836 430 308 696 843 114 214 328  51 221
 312 236  55 362 593 313 887 377 794 564  58 739 828  39  29 277 429  63
 152 294 210 422 806 463 178 368 803 707 324 598 724 176 102 681  18 281
 345 670 680 823 588 403 697 493 296  76 248 289 366 685  71 128 742 442
 519  85 818 702 643 241 427 557 262 746 708 242 488 392 854 182 776 135
 592 468 437  45 866 409 215 413 141 826 290 158 278 753 626 337 171 315
 787  25 615 706 784 188  20 888 428 287 386 301  83 489 703 536 452 814
 511 165 304 116  30  12 335 197 295 216 721 534 625 156 192 771 269 780
 173 371 350 495 228  81 434 872 857 796  16 610  38 459 642 258 305 502
  40 240  27 490 407 131 500 424 226 548 130 382 504 775 483  36 136 540
 492 406 551 864 401  48 849 212 783 690 606 497 184 861 229 211 180 206
 280 249 491   0 712 279 687 395 505  94 815 730  65 798 378 201 876 590
 713 604 717 440 583 539 858 829 285 726 441  92 198 788 326 603 385 425
 526 827 882 146 244 737 217 520  62 618 837 792 531 119  53 574 213 573
 100 108 177 774 863 218 735 822 667 657 732 614 311 749 162 150 376 369
 779 684 527 223 306 467  19 391 106 661 259 734  21 456 485 791 257 743
  93 553 417 303 879  82 349  42 518 805 867 421 597 652 528 247 532 235
 412 360 408 786 549  34 584 359   2  64 839 756 543 546 627 230 723 594
 565 572 153 768 347 512  77 105 444 507 396  41 769 341 443 358 575 159
 679 142 496 149 190 577 145 383 802  89  22 508 439 650 342 414 264   1
 122 487 637 299 725  75 745 770 254 499 137 154 852 666 419 172 514 517
 183 475 310  95 503 297 356 354 355 651 373 329 515   5 498 602 883 589
 132 830 115 390 630 170 462 272 878 227 555 731  43 689 121 778 479 465
 561 523 810 569 773 761 759 579  59 744 595 238 332 552 873 320 824 635
 760 375 330 275 596  15  74 353 286 711 273 641 194 372 367  91 155 754
 267 874 476 186 880 677 381 653 662 530 890 671 196 298 112 715 398 255
 750  67  32 509  44 222 570  46 433 838 464 415 365 101 164 560 809 423
 694  23  69 762 841 719 747 288  99 647 271 293 431 169 253 432 659 619
 545 331 151 693 881 189 758  24 453 333 889 692  14 691  97 733 722 571
 410 389 357 477 559 129   6 611 648 338 256 688 232 161 319 790 675 847
 695 855 566 623 460 825 646 193 629  28 718 766 640 181 450 663  87 535
 581 544 795 728 510 800   9 521 654 832 804 674  79 276 609 225  13 669
 393 380 340 300  96 764 133 616 835]
[126 886 853 480  50 741 361  60 314 844 785 447 234 748 524 819  61 123
 482 622 266 628 404  72 676 160 533 811 727 209 166 556 585 772 686 265
 474 850 582 729 388 793  68 789 578 473 185 831 807 111 402 205 138  10
 187 472 420 399 848 455 200 562   3 307 203  73 268 834 233 103 445 486
 870 851 621 655 672 682 840 869 270 632 865 736 208 394 525 664 613 207]
[541 746 227 758 112 656 741 481 564 346 247 858 597 778 476 480 807 733
 309 833 692 385 164 437 728 856 788 727  84 867  11 234 300 277 504 776
 777 329 228 370 196 863  19 459 471 261 134 212 294 635 268  25 170  61
 712 444 382 683 534 147 821  41  79 267 798 633 715 230 360 576 546 254
 874 118 262 157   8 859 606 128  52 784 237 207 592 177 313  15 130 181
 318 810 803  34 429 354 601 483 782 701 745 198 308 695 497 657 742   4
  30 451 575 358 813  10 593 888 713  43 809 769 327 442 686 530 290 307
 795 258 688 323 405 650 637 373 629 774 465 622 206 430 672 383 441 486
 353 572 347  63 302 367 461 402 717  60  78 286  86 649 289  24 655 625
 738 287 371 116 244 193 172 314 200 440  14 766 871 642  50   5 283 703
 785 735 449 412 753 557  32 811 406 160   6  66 352 563 269  16 490 336
 243 852 115 117 796 834   0  69 403 724 447 533 889 305 395 652 276 614
 881 105 400 664 450 219 317 229 380 133 835 205 861 750 368 600 204 780
 208 644 316 156 260 322 848 709 553   2 474 726 880 389 142  39  23 570
 310 222 596 662 882 303 702 636 870  72 169 311 747 194 517 201 433 284
 545 431 218  64 790 743  96 427 331 820 493  45 463 111 792 137  48 812
 854 146 348  57 454 114 195 594 319 818 599 381 838 527 495 413 214 505
 651 349 878 551 661  22 375  70 518 113 556 749 138 390 890 654 595 472
 401 582 477 328 831 411  62 789 706 574 814 140 426 443 350 240 491 161
 332 805 487 578 581 605 398 301 149 875 532 124  38 259 826 586 737 554
 176 356 675 602 296 224 872 503 673 647 756 298 167 873 221 643 783 822
 272 620  82 239 275 458 341 511 839   1 340  33 236 580 507 585 374 607
 523 376 397 667 559 223 739 804 836 446 387 315 216 203 846 498 110 422
 435 122 536 215 420 136 357 722 700 326 242 646 404 330 877   9  74 548
 485 197  83 436  29 126 689 509 131 418  80 280 178 417 456 104 694 512
 725 761 502 256 744 853 251 519 211 668 671 825 615  54 641 577 674 337
 590 837 231  81 325 199 687 608 521 609 191 819 591 288  71 333 612 764
 407 292 285 393 501 516 698 438 293 771 143 462  67 860 320 388 711 173
  18 791 392 648  75  99 522 100 794 252 494 793 391 800 141 514 421 455
 751 510 525 569 885 478 159  28 217 183 129 618 153 299 335 202 755 188
 634 734 752 568  53 108 565  85 729 342 524 515 500  47 526 189 464 817
 732 351  92 799 386 154  94 631 849 345 663  93  40 468  76 152 249 513
 460 226 841 155  51 588 213 828 587 865 338 529 632 704 282 781 584 707
 659 731 699 274  49 823 506 484 638 135 537 119 297 617  31 763 787 773
 721 623  88 439 508 690 669  87 175 621 797 102 718 681 535 174 432 363
 467 684 165 192  44  77 428  89 619 705 488 220 760 103 547 627 555 719
 561 845 409 106 579 639 408 255 291 238 611 424 730 145 542  26  20 264
 857 603 685 359 550 708 473 544 107 680 419 245 423 416 266 232 187 562
  37 691  91 802 343 610 855 379 295 767 539 696 531 808  58 466 714 324
 543 884 257 560 180 265 366 844 624 185 457 604 540   7 682 184 321 759
 740 279 626 720 179 883 658 127 163 598 697 496 779 499 736 151 469 670
 616 613 754 425 815 334 233 246 552 876 768 640 166 270 415 248 339 710
 748 765 850 210 168 772 666 414 452 378 101 306  55 566 410 573 816 190
 109 186 583  98  73  35 144  65  56 162   3 665 630 479 148 843 677 120
 571 887  68 362 851  97 678 396 589]
[271 372 369 344  95  21 470 365 482 660 770 281  59  12  46 762 693 775
 364 558 171 628 434 676 567 241 304 847 549 723 866 475 312 489 453 125
 879 253 679 445 827  13  90 862 840 830 757  27 235  17 377 868 139 538
 528 716 182 250 132 520  36 832 653 384 645 786 824 864 842 829 492 394
 801 806 121 263 123 278 273 448 225  42 869 355 886 361 158 209 399 150]
[653  93 652 105 839 344  37 794 117 862 514 349 175 139 393 773 391 315
 442 535 123 516 487 710 312 143 619 321 347 113 206 444 491 152 170 616
 844 230 300 222  52 596 777 585 706 392 437 694 583 174 783 886 471  29
 855 723  54 210 500 510 544 220 717 603 326 110 828 301 630 204 337 260
 834 488 758 504 833 450 200 649 592 412 305 765  33 257 523 403 355 434
  95 689  48  64 319 188  68 543 441 754 676 736 335 642 327 255 463 303
 650 746 167  23 540 409  27 571 350 130 567  30 288 142 236 461 182 875
 348  50 657 752 766 555 165 734 275 172  70 179 607 377 209  99 360  59
 259 606 740 425 686 159 817 814  82 604 755 591 492 496 411 778 629 537
 864 456 307 779 651 609 485 770 373 704  39 239  35 329 448 658 709 763
 605  62 879 498  21 419 261  43 432 732 705 622 764 646 581 296 745 812
 692 690 125 121 225 832 178 389 856 525  34 713 559 776 388  17 124 241
 513 256 345  57 857 639 476 341 823 449 380 306 196 724 625 798 145 796
 671  90 638 594 378 884 285 772 273 722 214 870  84 863 771 374 242  53
 748 663 202 762 627 473 235 531 578 580 654 111 885  69 800 291  76  13
 786 809 137 757 287 215 154 368 691 244 792 815 582 836 667 682 737 837
 716 615 489 398  47 813 181 675  63  78 416 334 561 268 140 876 738  87
  44 342 134 595 726 610 550 873 246 211 593 519 247  49 376 785 720 600
 819 536 484 790 522 199 782 338 160 853 176 759  15 316 278 618 339 818
 674 193 249 647 122 446 359 843 478 219 293 135 186 298  32 509  96 612
 169 702 551 643  91 613 744  86 520  79 479 784  83 354 733 669 413 302
 161 824 679 731 825   1 735 189 158 756 524 547 104 670 465 587 280 556
 685 869  28 508 846 454 495  19 787  46  24 212 238 743 264 697 810 847
 102 576 645   3  73 527  88 213 217 422 482 228  72 698 701 346 859 640
 443 517 270 566 827 353  89 568 216 708 887 289 371 624 292 845 400 718
 711  61 599 313 381 835 803 191 564 866 518 598 462   9 474  36 672 363
 407 659 129 634 358  81 662  66 560 223 590 428 436 725 266 661 620 660
 390 173 890 417 548 558 126 468 203 501 251 512  20 793 351 557 747 883
  74 101 533 840 362 546 739 208 753 364 614 325 375  51 797 232 108 198
 420 553 668 680 696 572 584 282 457 601 589 171  31  45 369  80 438 352
 831 807 830 666 816 806 144 106 878 429 427 805  58  85 240 781  26 539
  97 410  98 279 372 237 573 480 459  22 166 397 673 136 721 185 577   8
 768 221 156 841 490 789 579  41 197 494 379 703 263 424 455 821 452 469
  14 146 414 297 493  40 281 467 163 730 385 356 808 318 187 361 331 155
 865   0 811 383 503   5 190 829 611 570  12 882 486 405 700 153 332 677
 453 418 802 688 507 880   6 310 483 588 695  16 741 127 258 141 195 874
 138 529 401 641 304 472 497  10 227 218 505 406 854 323 253 569  60 742
 320 340 299 149  25 714 150 399 575 868 290 750 224 295 871 133 530 470
 621 545 233  92 799 849 245 665 466 387   4 851 852 678 252 728  65 366
 408 502 608 481 526 447 272 769 867 631  94 423 107  42 283 586 822 265
 276 116 848 421 431 308 637 309 715 534 205 269 426 460 636 729 775 648
 445 229 877 382 248 330 194  38 574 451 635 628 780 164 115 114 788 262
 881 842  56 100 528 402 254 712 683 274 148 328 687 656 207 396 415 563
 644 177 294 404 655 699 439 499 826 128 243 515  75 109 324 664 521 861
 277  18 430 103 168 767 201 511 850]
[761 626 562 271 119 333 147 838 820 317 314 267 184 386 284  11 365 538
 112 151 394 336 183 157  55 597 343 751 180 541 804 565 433 542 889 858
 250 120   7 458 554 311 693 681 719 617 872 602 749 370 727 357 707 860
 131 801 477 435 791 632 532 440  71 888 322 795 623 367  77 231 384 286
   2 118 549 192 552 162 464 760 633 395  67 506 684 475 226 774 234 132]
[867 457 597 851 529 312 863 586 705 778 421 192 601 213 493 438  34 622
 259  58 505 617 547 203 569 227 764 706 436 324 360 633 702 142 409 105
 831 247 545 511 189 183  19 494 265 386 467 274 166 437 331 254 125 158
 673 567 497 613 148 363 575 576 846 566 244 789 153 487 268 434 470 392
 803 587 806  61 872 535 630 440 354 709 369 406 135 223 413 209 271 482
 759 866  85   2 242  18 503 573 681 258 288 790 628 534 145 853 620 159
 879 377 592 665 270 869 700  10 210 267 224 809 781 626 302 245 284 234
 340 885 749 155 329 238 488 583 187 714 464 498 347 461  37 182 186  31
 683 855 272 829 632 631 206 751 394  69 212 149 460 818 873 197 651 826
  93 151 635 344 760 334 878 232 845 679  22  51 127 841 110 416 319 610
 370 783 170 678  62 174  23 388 786 541 528 300 299 152 479 596  15 776
 381 562  68 520 450 468 611 577 390 887 477 426 454  56 710 883 800  38
 696 353 559 656 669 604 216  96 200 414 451 342 305 269  71 251 471 739
 346 345 277 111 286  53 495 738  50 458 373 849 301 169 310 435 685 350
  42 600 175 352 162 797 652 276 273  39 349 509 122 399 398 832 602 805
 649 328 397 205 408 721 641 147  60 418 677 856   5 740 143 546  99 708
 283 472 315 827 558 523 599 447 543 648 653 201  43 237 758  81 133 374
 808 275 240 131 261 139 792 154 180 304 798 590 663 389 774 219 132  55
 144 593 799 306 724 550 578 822 307 655 507 380 383 812  49 515 513 607
 103 452 235 341 703 463 732 796 695 230 880 722 168 756 257 745 338 817
 194  78 553 384 830 859 526 321 707 780 483 711 260 140 712 101 686 453
 112 486 857 743 326 249 428 741  77  32 728 552 492 623 765   0 395 642
 357 167 582 645 890 727 659  94 684 639 572 296 556 179 828  33 530 693
 499 356 126 782 640 726 802 854 297 813 130 614  25  41 320 768 225 755
 733  75 767 465 412 415 868 358  66 752 446 598 519 322 172  13 480 804
 668 250 698 443 441 823 314 215 836 647 150 425 875 207 372 720 348 262

In [16]:
train_index.shape, test_index.shape

((801,), (90,))

In [25]:
del train_index
del test_index

In [20]:
pd.DataFrame(train).isnull().count(), pd.DataFrame(test).isnull().count()

(Unnamed: 0    891
 Survived      891
 Pclass        891
 Sex           891
 Age           891
 Fare          891
 Embarked      891
 FamilySize    891
 IsAlone       891
 Title         891
 dtype: int64, Unnamed: 0    418
 Pclass        418
 Sex           418
 Age           418
 Fare          418
 Embarked      418
 FamilySize    418
 Title         418
 IsAlone       418
 dtype: int64)

In [27]:
for train_index, test_index in samples.split(X,y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    print(X_train.shape, X_test.shape)
    print(y_train.shape, y_test.shape)

KeyError: '[349 134 487 519 225  30 129 580 103 649 128 137 209 177 809 542 404 632\n 130 475 254 385 266 290 686 119 300 285 464 131 843 703 456 255 234 341\n 430 444 662  66 124 447 698 605 116 844 299 702 102 614 775  27  58 427\n 410  77 123 830  18 238 529 685 826 164 799 690 885 839   2 438 591 226\n 638 409 556 120 126 125 537 567  86 327 545 755 787  13 472 560 797 823\n 170 135 117 288 305 503 233 147 767 435 273 717 619 513 520 523 432 471\n 247 152 530 563 550 516 399  89 804 198 802 596 240 262  35 581 814  12\n 509  67  29 515 590 757 205 776 594 588 807 150 283 714 665 571 627 319\n 308 848 424  65 652 180 357  81 148 522 312 762 364 185 406   6 190 750\n 352  47 634 201  59 369 883 538 793  41 525 463 880 602 859 849 189 257\n 536 239 159 695 114 264 697 479 315 309 527 615 524 484 803 656 606 789\n 366  56 488 166 429 636 663 470  95 473 667 461 269 163 688 806 608 242\n 815 733 783 338 505  99 584 650 365 756 351  17 681 310 600 379 732 684\n 820 183 860 498 771 701 821 715 219 546 502 630 199 693 873 232   1  19\n 575 554 621  57 613  82  49 382 604 249 453 570  40 151 528 393 455 263\n 812 286 306 673 386  50 585 436 862  11 654 441 758 465 817 106  62 317\n 850 845 331 462 612 744 670 346 203 101 837 371 448 739 497 816 113  24\n 167 819 532 772  61 127 766 858 562 350 329 110 539 564 105 454 707 478\n 531 841 274 710 354 268 659  74 215 765 752 521 179 857 805 380 623 138\n 426 889 449 553 348 321 200  20 334 624 867 692 796 111 810 356 811  39\n 699  37 298 890  22  31  43 691 625 140 779 610 378 370 422 153 367 651\n 565 387 832  23  96 265 589 342 451 139 616 303 786  16 174 548 886  15\n 173 734 194 252 853 372 413   5 738 358 877   8 742 156 373 682 256 316\n 227 425 218 836 210 660 326 543 343 887 568 743 221  69 467 719  21 499\n  80 555 773 360 281 881 347 388 648 782 375 716 376 277 769 184  72 728\n 828 469 204 408 253 322 726 398 876 446 593 243 325 212 852 617  91 653\n 633 753  92 480 639 780 333 149 763  28  84 501 214 122 865 547 313 647\n 459 791   0 162 729  63 874 781 235 540 496 720 175 208 551   4 718 136\n 434 582 482 706 512 785  45 642 784 318 477 708 222 397 328 390 722 700\n 759 259  88 494 607 421 861 559  85 241 304 500 244 324 611 704 485 671\n 433 287 888 236 457 157 552 414 301 696 272 431 601 402 423 856 230 535\n 644 246 359 192 583 740 834  70 829 526 678 609 458  73 295 213 133 518\n  64 689 374  55  93 291 420 725 490 121 549   9 777 731 741 468 587 452\n 311 362 144 237 340 747 855 669 146 822 108 631 450 245 216 335 155 320\n 626  60  38 723 770 599 411 207 798 573 847  94 363 171  68  76 760 332\n 679 884 276 270 384  78 104 840 416 510 181 749 248 282  83 289 788 418\n 569 400 292 635 827 871 872 730 646 661  46 158 160 712 460 489 658 705\n 761 517 578 280 381 132 250 764 687 870 576 869 344 748  25 813  34 875\n 439 514  79 795  52 745 754 278 172 251 674 713 664 595 261 293 186 579\n 231 668 345 115  36 574 620 868 677 314 193  10  14  75  48 736 195 228\n 109 481 412 629 107 307 154 141 491 561 863  32 297  90 879 557 220 628\n 825 339 778 182 878 492 391 735  97 835 187  98 323 774  42 442 711 217\n 165 294 882  53 466 504 866 476 260 655 302 508 724 534 407 544 395 746\n 419 694 603 112 296 337 666 178 833 118 622 415 403 202  71 197 507 474\n 191  33 206 794 161   7 598 846 533] not in index'

In [21]:
from sklearn.linear_model import LogisticRegression

In [23]:
log_reg = LogisticRegression()
log_reg.fit(X,y)
y_pred = log_reg(test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [24]:
X = X.drop(['Unnamed: 0'],axis=1)

In [25]:
X.columns

Index(['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize', 'IsAlone',
       'Title'],
      dtype='object')

In [26]:
test.columns

Index(['Unnamed: 0', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize',
       'Title', 'IsAlone'],
      dtype='object')

In [27]:
test = test.drop(['Unnamed: 0'], axis=1)

In [28]:
log_reg = LogisticRegression()
log_reg.fit(X,y)
y_pred = log_reg(test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [29]:
test.isnull().sum()

Pclass        0
Sex           0
Age           0
Fare          1
Embarked      0
FamilySize    0
Title         0
IsAlone       0
dtype: int64

In [30]:
test.Fare.isnull().values.any()

True

In [31]:
test[test['Fare'].isnull()]

     Pclass  Sex  Age  Fare  Embarked  FamilySize  Title  IsAlone
152       3    1    4   NaN         0           1      1        1

In [32]:
test['Fare'].iloc[152]

nan

In [33]:
avg = test['Fare'].mean()

In [34]:
test['Fare'].iloc[152] = 2
test['Fare'].iloc[152]

C:\Users\ankish\Anaconda3\lib\site-packages\pandas\core\indexing.py:194: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

2.0

In [35]:
test.Fare.astype(int)

0      0
1      0
2      1
3      1
4      2
5      1
6      0
7      3
8      0
9      3
10     1
11     3
12     4
13     3
14     4
15     3
16     2
17     0
18     1
19     0
20     4
21     0
22     3
23     4
24     4
25     2
26     4
27     0
28     3
29     3
      ..
388    0
389    2
390    4
391    3
392    2
393    1
394    3
395    4
396    0
397    4
398    0
399    0
400    4
401    2
402    4
403    4
404    3
405    2
406    1
407    4
408    0
409    2
410    0
411    4
412    0
413    1
414    4
415    0
416    1
417    3
Name: Fare, Length: 418, dtype: int32

In [36]:
X.isnull().any()

Pclass        False
Sex           False
Age           False
Fare          False
Embarked       True
FamilySize    False
IsAlone       False
Title         False
dtype: bool

In [37]:
X[X['Embarked'].isnull()]

     Pclass  Sex  Age  Fare  Embarked  FamilySize  IsAlone  Title
61        1    0    3     4       NaN           1        1      2
829       1    0    4     4       NaN           1        1      3

In [38]:
X['Embarked'].median()

0.0

In [39]:
X['Embarked'].iloc[61] = 0
X['Embarked'].iloc[829] = 0

C:\Users\ankish\Anaconda3\lib\site-packages\pandas\core\indexing.py:194: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [40]:
X.isnull().sum()

Pclass        0
Sex           0
Age           0
Fare          0
Embarked      0
FamilySize    0
IsAlone       0
Title         0
dtype: int64

In [41]:
y.isnull().sum()

0

In [42]:
test.isnull().sum()

Pclass        0
Sex           0
Age           0
Fare          0
Embarked      0
FamilySize    0
Title         0
IsAlone       0
dtype: int64

In [44]:
X.head()

   Pclass  Sex  Age  Fare  Embarked  FamilySize  IsAlone  Title
0       1    1    1     0       1.0           1        1      1
1       1    0    3     4       1.0           2        0      3
2       3    0    2     1       0.0           1        1      2
3       1    0    3     4       0.0           2        0      3
4       3    1    3     1       0.0           1        1      1

In [45]:
y.head()

0    1
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [46]:
test.head()

   Pclass  Sex  Age  Fare  Embarked  FamilySize  Title  IsAlone
0       3    1    3   0.0         2           1      1        1
1       3    0    4   0.0         0           2      3        0
2       2    1    4   1.0         2           1      1        1
3       3    1    2   1.0         0           1      1        1
4       3    0    1   2.0         0           3      3        0

In [48]:
X.to_csv("X_data.csv")
y.to_csv("y_data.csv")
test.to_csv("test.csv")

In [49]:
log_reg = LogisticRegression()
log_reg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [50]:
log_reg.params()

AttributeError: 'LogisticRegression' object has no attribute 'params'

In [51]:
log_reg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [52]:
y_pred = log_reg.predict(test)

In [53]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0],
      dtype=int64)

In [54]:
count = 0
total = 0
for i in y_pred:
    if i == 0:
        count += 1
    total += 1

print("class: 1 ==>", total-count)
print("class: 0 ==>", count)

class: 1 ==> 144
class: 0 ==> 274

In [55]:
y_pred[1]

0

In [56]:
samples

StratifiedShuffleSplit(n_splits=10, random_state=0, test_size=0.1,
            train_size=None)

In [58]:
test_index

array([158, 631, 376,  81, 856, 676, 763,   7, 757, 336, 203, 724, 588,
       536, 154, 587, 493, 596, 348, 530, 360, 113, 644, 378, 511, 422,
       130, 865, 597, 458,  45, 455, 773, 358, 220, 521, 568, 398, 787,
       603, 678, 311,  52, 768, 507, 264, 795, 850, 303, 646, 284, 633,
       722,  31, 269, 241,   2, 718, 533, 882, 669, 593, 263, 392, 401,
       178,  94, 571, 565,  49, 495, 670, 737, 617, 859, 249, 202, 611,
       561, 756, 599, 471, 374, 429, 119, 464,  75, 519, 393,  77],
      dtype=int64)